### ISSUE TITLE
Italian.po file with wrong words

### ISSUE THREAD

**Issue by Luigi-C** [sdottaka/winmerge-v2-jp#1]
Hi, in experimental release WinMerge 2.14.0 + (3-way merge, image compare/merge) +-jp-152 the file Italian.po contains three wrong words "Sì", that should be replaced with "Si" (not accented "i").

**Comment by sdottaka** [comment]
Thank you for the report.
Are the three "Sì" as follows?
~~~
#: Merge.rc:29CE40
#, c-format
msgid "Yes"
msgstr "Sì"

#: Merge.rc:22956AA
#, c-format
msgid "&Yes"
msgstr "&Sì"


#: Merge.rc:48B5872E
#, c-format
msgid "Yes to &all"
msgstr "Sì a &tutto"
~~~

I can not read Italian, but "Sì" seems to be appropriate as it is equivalent to "Yes" in English... 

Also, I'd be happy to have a pull request at https://github.com/sdottaka/winmerge-v2 instead of this repository.

You can edit directly on GitHub from the following URL and create Pull Request.

https://github.com/sdottaka/winmerge-v2/blob/master/Translations/WinMerge/Italian.po

**Comment by Luigi-C** [comment]
The appropriate italian word for the english "Yes" is "Si", where the "i" is not accented.

**Comment by sdottaka** [comment]
Fixed in https://github.com/sdottaka/winmerge-v2/commit/2c9a1d0def6fecbcd4b92fe946d861ab7b7cfb7c
